apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spigot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spigot
    spec:
      containers:
      - name: spigot
        image: registry.ng.bluemix.net/brownkyl/spigot-plugin-bluemix
---
apiVersion: v1
kind: Service
metadata:
  name: spigot-service
  labels:
    run: spigot
spec:
  selector:
    app: spigot
  type: NodePort
  ports:
   - protocol: TCP
     port: 25565
