name: WatsonConversationPlugin
main: com.ibm.minecraft.spigotplugin.WatsonConversation
version: 1.0

commands:
  hello:
    description: A new command
  watson:
    description: watson initial command

